spring:
  application:
    name: batch
  profiles:
    active: local

  config:
    import:
      - logging.yml
      - db-core.yml

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod
